<?php
    /**
    * Setubridge Technolabs
    * http://www.setubridge.com/
    * @author SetuBridge
    * @license http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
    **/
?>
<?php
    $config = Mage::getStoreConfig('moreview_section/general_group/module_moreview');
    if($config):  
        $_helper = $this->helper('catalog/output');
        $_product=$this->getProduct();
        $imagesCount = Mage::getModel('catalog/product')->load($_product->getId())->getMediaGalleryImages();
        if(count($imagesCount) >1 ):
            $_images = $imagesCount->getItemByColumnValue('label', 'back');
            if($_images):
                $isResize=Mage::getStoreConfig('moreview_section/general_group/resize_moreview');
                if($isResize):
                    $_imgSize=Mage::getStoreConfig('moreview_section/general_group/resize_moreview_width');
                    else:
                    $_imgSize = 135;
                    endif;

            ?>
            <img class="sbmoreview" id="sbmoreview-<?php echo $_product->getId() ?>" src="<?php echo $this->helper('catalog/image')->init($_product, 'thumbnail', $_images->getFile())->resize($_imgSize); ?>" alt="<?php echo $this->htmlEscape($_images->getLabel());?>" title="<?php $this->htmlEscape($_images->getLabel());?>"/>

            <?php endif;?>
        <?php    endif; ?>
    <?php    endif; ?>