<?php

    /**
    * Setubridge Technolabs
    * http://www.setubridge.com/
    * @author SetuBridge
    * @license http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
    **/
?>
<?php   
    $config = Mage::getStoreConfig('moreview_section/general_group/module_moreview');
?>
<?php if(count($this->getItemCollection()->getItems())): ?>
    <div class="box-collateral box-up-sell">
        <h2><?php echo $this->__('You may also be interested in the following product(s)') ?></h2>
        <table class="products-grid" id="upsell-product-table">
            <?php // $this->setColumnCount(5); // uncomment this line if you want to have another number of columns. also can be changed in layout ?>
            <?php $this->resetItemsIterator() ?>
            <?php for($_i=0;$_i<$this->getRowCount();$_i++): ?>
                <tr>
                    <?php for($_j=0;$_j<$this->getColumnCount();$_j++): ?>
                        <?php if($_link=$this->getIterableItem()): ?>
                            <td>
                                <a href="<?php echo $_link->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_link->getName()) ?>" class="product-image">

                                    <?php
                                        $sb=0;
                                        if($config == 1):
                                            $imagesCount = Mage::getModel('catalog/product')->load($_link->getId())->getMediaGalleryImages();
                                            if(count($imagesCount) >1 ):
                                                $_images = $imagesCount->getItemByColumnValue('label', 'back');
                                                if($_images)
                                                {
                                                    $sb=1;
                                                ?>
                                                <img class="sbmoreview" src="<?php echo $this->helper('catalog/image')->init($_link, 'thumbnail', $_images->getFile())->resize(125); ?>" alt="<?php echo $this->htmlEscape($_images->getLabel());?>" title="<?php $this->htmlEscape($_images->getLabel());?>"/>
                                                <?php } ?>
                                            <?php    endif;?>
                                        <?php endif ?>                                        
                                    <img class="<?php if($sb==1)echo "sbview";?>" src="<?php echo $this->helper('catalog/image')->init($_link, 'small_image')->resize(125) ?>" width="125" height="125" alt="<?php echo $this->htmlEscape($_link->getName()) ?>" /></a>
                                <h3 class="product-name"><a href="<?php echo $_link->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_link->getName()) ?>"><?php echo $this->htmlEscape($_link->getName()) ?></a></h3>
                                <?php echo $this->getPriceHtml($_link, true, '-upsell') ?>
                                <?php echo $this->getReviewsSummaryHtml($_link) ?>
                            </td>
                            <?php else: ?>
                            <td class="empty">&nbsp;</td>
                            <?php endif; ?>
                        <?php endfor; ?>
                </tr>
                <?php endfor; ?>
        </table>
        <script type="text/javascript">decorateTable('upsell-product-table')</script>
    </div>
    <?php endif ?>

