<?php
    /**
    * Setubridge Technolabs
    * http://www.setubridge.com/
    * @author SetuBridge
    * @license http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
    **/
?>
<?php if($this->getItemCount()): ?>
    <div class="crosssell">
        <h2><?php echo $this->__('Based on your selection, you may be interested in the following items:') ?></h2>
        <ul id="crosssell-products-list" class="products-grid products-grid--max-3-col">
            <?php foreach ($this->getItems() as $_item): ?>
                <li class="item">
                    <a class="product-image" href="<?php echo $_item->getProductUrl() ?>" title="<?php echo $this->escapeHtml($_item->getName()) ?>">

                        <?php
                            $config = Mage::getStoreConfig('moreview_section/general_group/module_moreview');
                            if($config==1)
                            {
                                $sb=0;
                                $imagesCount = Mage::getModel('catalog/product')->load($_item->getId())->getMediaGalleryImages();
                                if(count($imagesCount) >1 ):
                                    $_images = $imagesCount->getItemByColumnValue('label', 'back');
                                    if($_images)
                                    {
                                        $sb=1;
                                    ?>
                                    <img class="sbmoreview" src="<?php echo $this->helper('catalog/image')->init($_item, 'thumbnail', $_images->getFile())->resize(210); ?>" alt="<?php echo $this->htmlEscape($_images->getLabel());?>" title="<?php $this->htmlEscape($_images->getLabel());?>"/>
                                    <?php }

                                    endif;
                        }?>

                        <img class="<?php if($sb==1)echo "sbview";?>" src="<?php echo $this->helper('catalog/image')->init($_item, 'thumbnail')->resize(210); ?>" alt="<?php echo $this->escapeHtml($_item->getName()) ?>" />
                    </a>
                    <div class="product-details">
                        <h3 class="product-name"><a href="<?php echo $_item->getProductUrl() ?>"><?php echo $this->escapeHtml($_item->getName()) ?></a></h3>
                        <?php echo $this->getPriceHtml($_item, true) ?>
                        <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_item) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                        <ul class="add-to-links">
                            <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                <li><a href="<?php echo $this->getAddToWishlistUrl($_item) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
                                <?php endif; ?>
                            <?php if($_compareUrl=$this->getAddToCompareUrl($_item)): ?>
                                <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
                                <?php endif; ?>
                        </ul>
                    </div>
                </li>
                <?php endforeach; ?>
        </ul>
        <?php // <script type="text/javascript">decorateList('crosssell-products-list', 'none-recursive')</script> ?>
    </div>
    <?php endif; ?>
